fix(bootstrap): use double loop like original (Docs) to avoid breaking at timeouts

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -6,8 +6,6 @@
 
 set -eu
 
-# source "${HOME}/.config/yadm/scripts/colors.sh"
-
 # Directory to look for bootstrap executables in
 BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
 
@@ -16,13 +14,17 @@ if [[ ! -d "${BOOTSTRAP_D}" ]]; then
   exit 1
 fi
 
-find -L "${BOOTSTRAP_D}" \( -type f -or -type l \) -not -name '*##*' -not -name '*~$*' | sort -n |
-  while IFS= read -r bootstrap; do
-    if [[ -x "${bootstrap}" ]]; then
-      printf "%s\n" "Executing ${bootstrap} ..."
-      if ! "${bootstrap}"; then
-        echo "Error: bootstrap '${bootstrap}' failed" >&2
-        exit 1
-      fi
+declare -a bootstraps
+while IFS= read -r bootstrap; do
+  bootstraps+=("$bootstrap")
+done < <(find -L "${BOOTSTRAP_D}" \( -type f -or -type l \) -not -name '*##*' -not -name '*~$*' | sort -n)
+
+for bootstrap in "${bootstraps[@]}"; do
+  if [[ -x "${bootstrap}" ]]; then
+    echo "Executing ${bootstrap}"
+    if ! "${bootstrap}"; then
+      echo "Error: bootstrap '${bootstrap}' failed" >&2
+      exit 1
     fi
-  done
+  fi
+done
